version: '3'
services:
  notebook:
    build: .
    #image: eywalker/pytorch-jupyter:v0.4.0-updated
    env_file: .env
    entrypoint:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=$JUPYTER_PASSWORD
      - --no-browser
    ports:
      - "9990:8888"
    volumes:
      - ./notebooks:/notebooks/local_notebooks
      - /mnt/lab/users/eywalker/notebooks:/notebooks/lab_notes
      - /tmp:/tmp
      - /mnt/dj-stor01:/external
      - /mnt/lab/microns/data:/data
      - .:/src/neuro_data
